[package]
name = "Vision"
version = "0.1.0"
authors = ["Thomas Herzog <batthomas@gmx.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
winit = "0.24.0"